__version__ = '0.0.18'
__author__ = 'Loris Henrion'
__author_email__ = 'loris_henrion@bce.lu'
__description__ = 'Syncing permissions and tenant on IP Addresses and VLANs with those from their corresponding Prefix in NetBox'
__license__ = 'GPL-3.0'
__url__ = 'https://github.com/LoH-lu/netbox_ip_permissions_synchronization/'
